prompt 6 fix 1, time 0:00:10
on `flutter run" i get error:
```
Launching lib\main.dart on Windows in debug mode...
lib/main.dart(55,12): error G5FE39F1E: Type 'SmaData' not found. [testai-chart-quotes\testai_chart_quotes\build\windows\x64\flutter\flutter_assemble.vcxproj]
lib/main.dart(57,20): error G3A27A24F: 'SmaData' isn't a type. [testai-chart-quotes\testai_chart_quotes\build\windows\x64\flutter\flutter_assemble.vcxproj]
lib/main.dart(61,19): error GE5CFE876: The method 'SmaData' isn't defined for the type '_CurrencyQuotesAppState'. [testai-chart-quotes\testai_chart_quotes\build\windows\x64\flutter\flutter_assemble.vcxproj]
lib/main.dart(361,40): error G3A27A24F: 'SmaData' isn't a type. [testai-chart-quotes\testai_chart_quotes\build\windows\x64\flutter\flutter_assemble.vcxproj]
lib/main.dart(363,46): error G3A27A24F: 'SmaData' isn't a type. [testai-chart-quotes\testai_chart_quotes\build\windows\x64\flutter\flutter_assemble.vcxproj]
lib/main.dart(364,46): error G3A27A24F: 'SmaData' isn't a type. [testai-chart-quotes\testai_chart_quotes\build\windows\x64\flutter\flutter_assemble.vcxproj]
lib/main.dart(381,9): error GB4CD8C76: 'class' can't be used as an identifier because it's a keyword. [testai-chart-quotes\testai_chart_quotes\build\windows\x64\flutter\flutter_assemble.vcxproj]
lib/main.dart(381,15): error G67247B7E: Expected ',' before this. [testai-chart-quotes\testai_chart_quotes\build\windows\x64\flutter\flutter_assemble.vcxproj]
lib/main.dart(381,23): error G67247B7E: Expected ',' before this. [testai-chart-quotes\testai_chart_quotes\build\windows\x64\flutter\flutter_assemble.vcxproj]
lib/main.dart(382,11): error G25387D61: Expected an identifier, but got 'final'. [testai-chart-quotes\testai_chart_quotes\build\windows\x64\flutter\flutter_assemble.vcxproj]
lib/main.dart(382,11): error G67247B7E: Expected '}' before this. [testai-chart-quotes\testai_chart_quotes\build\windows\x64\flutter\flutter_assemble.vcxproj]
lib/main.dart(351,65): error GC2F972A8: The argument type 'List<ChartSeries<dynamic, DateTime>>' can't be assigned to the parameter type 'List<CartesianSeries<dynamic, dynamic>>'. [testai-chart-quotes\testai_chart_quotes\build\windows\x64\flutter\flutter_assemble.vcxproj]
lib/main.dart(381,9): error G4127D1E8: The getter 'class' isn't defined for the type '_CurrencyQuotesAppState'. [testai-chart-quotes\testai_chart_quotes\build\windows\x64\flutter\flutter_assemble.vcxproj]
lib/main.dart(381,15): error G4127D1E8: The getter 'SmaData' isn't defined for the type '_CurrencyQuotesAppState'. [testai-chart-quotes\testai_chart_quotes\build\windows\x64\flutter\flutter_assemble.vcxproj] lib/main.dart(381,23): error G44692867: A value of type 'Set<dynamic>' can't be assigned to a variable of type 'Widget'. [testai-chart-quotes\testai_chart_quotes\build\windows\x64\flutter\flutter_assemble.vcxproj]
MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for 'testai-chart-quotes\testai_chart_quotes\build\windows\x64\CMakeFiles\0a0bf5c6ffc1ee804bf034410b9f1d7c\flutter_windows.dll.rule;testai-chart-quotes\testai_chart_quotes\build\windows\x64\CMakeFiles\a82677f4adc0184d08301f439432ca38\flutter_assemble.rule' exited with code 1. [testai-chart-quotes\testai_chart_quotes\build\windows\x64\flutter\flutter_assemble.vcxproj]
Building Windows application...                                     6,1s
Error: Build process failed.
```