prompt 5 fix 1, time 0:00:06
on `flutter run" i get error:
```
Launching lib\main.dart on Windows in debug mode...
lib/main.dart(231,35): error G7AA24C43: Local variable '_tfLabel' can't be referenced before it is declared. [testai-chart-quotes\testai_chart_quotes\build\windows\x64\flutter\flutter_assemble.vcxproj]
lib/main.dart(231,35): error GE5CFE876: The method '_tfLabel' isn't defined for the type '_CurrencyQuotesAppState'. [testai-chart-quotes\testai_chart_quotes\build\windows\x64\flutter\flutter_assemble.vcxproj]MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for 'testai-chart-quotes\testai_chart_quotes\build\windows\x64\CMakeFiles\0a0bf5c6ffc1ee804bf034410b9f1d7c\flutter_windows.dll.rule;testai-chart-quotes\testai_chart_quotes\build\windows\x64\CMakeFiles\a82677f4adc0184d08301f439432ca38\flutter_assemble.rule' exited with code 1. [testai-chart-quotes\testai_chart_quotes\build\windows\x64\flutter\flutter_assemble.vcxproj]
Building Windows application...                                     6,1s
Error: Build process failed.
```